name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine  # Added `twine` for verification

      - name: Build Package
        run: python -m build

      - name: Verify Package (Optional but Recommended)
        run: twine check dist/*

      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1  # Uses the official stable version
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
